from . import YOLO_WORLD_EfficientSAM
from . import YOLO_WORLD_SEGS

NODE_CLASS_MAPPINGS = {**YOLO_WORLD_EfficientSAM.NODE_CLASS_MAPPINGS, **YOLO_WORLD_SEGS.NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**YOLO_WORLD_EfficientSAM.NODE_DISPLAY_NAME_MAPPINGS, **YOLO_WORLD_SEGS.NODE_DISPLAY_NAME_MAPPINGS}
